### ISSUE TITLE
Boolean also accepts y/n

### ISSUE THREAD

**Issue by zerothi** [siesta-project/siesta-vim#3]
Perhaps this should be added for completeness sake.

Would changing:

`syn match  siestaBoolean   "\(\s\|^\)[tf]\($\|\s\)"`

to 

`syn match  siestaBoolean   "\(\s\|^\)[tfyn]\($\|\s\)"`

suffice?

**Comment by arthurfl** [comment]
It would! However n is already recognized as a unit (force), with 

`syn match siestaUnits "\(\s\|^\)[jkgmsnced]\($\|\s\)"`

So not sure how to handle that yet.. ideally, keywords expecting a boolean as argument should be differentiated so that there is some level of information on what will (can) be the argument, but that would add some level of complexity

**Comment by zerothi** [comment]
Ok, no worries, I think very few are using y/n anyway :)

2016-04-15 16:34 GMT+02:00 arthurfl notifications@github.com:

> It would! However n is already recognized as a unit (force), with
> 
> syn match siestaUnits "(\s|^)[jkgmsnced]($|\s)"
> 
> So not sure how to handle that yet.. ideally, keywords expecting a boolean
> as argument should be differentiated so that there is some level of
> information on what will (can) be the argument, but that would add some
> level of complexity
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/siesta-project/siesta-vim/issues/3#issuecomment-210484989

## 

Kind regards Nick
